{
 gSystem->Load("libHist.so");
 gSystem->Load("libGui.so");
 gSystem->Load("libThread.so");
 gSystem->Load("libNet.so");
 gSystem->Load("~/wasa/rootsorter/core/lib/libRSCore.so");
 gSystem->Load("~/wasa/rootsorter/core/lib/libRSClient.so");
 gSystem->Load("libXMLParser.so");
 gSystem->Load("~/wasa/rootsorter/core/lib/libRSXml.so");
 gSystem->Load("~/wasa/rootsorter/core/lib/libRSGClient.so");
 gSClient->GetSorterList(); 
 gStyle->SetPalette(1,0);
 gStyle->SetOptDate();
}
